#!/usr/bin/env python
# coding=UTF-8

import math, subprocess
import sys

p = subprocess.Popen(["ioreg", "-rc", "AppleSmartBattery"], stdout=subprocess.PIPE)
output = p.communicate()[0]

o_max = [l for l in output.splitlines() if 'MaxCapacity' in l][0]
o_cur = [l for l in output.splitlines() if 'CurrentCapacity' in l][0]

b_max = float(o_max.rpartition('=')[-1].strip())
b_cur = float(o_cur.rpartition('=')[-1].strip())

charge = b_cur / b_max
charge_threshold = int(math.ceil(10 * charge))

# Output

total_slots, slots = 10, []
filled = int(math.ceil(charge_threshold * (total_slots / 10.0))) * u'▸'
empty = (total_slots - len(filled)) * u'▹'

out = (filled + empty).encode('utf-8')

CSI="\x1B["
color_reset=CSI+"m"

color_green = CSI+"32m"
color_yellow = CSI+"1;35m"
color_red = CSI+"1;31m"
color_out = (
    color_green if len(filled) > 6
    else color_yellow if len(filled) > 4
    else color_red
)

# print color_red + "red" + color_reset
# print color_yellow + "yellow" + color_reset
# print color_green + "green" + color_reset

out = color_out + out + color_reset
sys.stdout.write(out)

